Dev
Alexeyvolsky/FinalSurge_Diploma_Volsky_Zaitsau pull request #2
Opened 2023-02-21 14:52 UTC by Alexeyvolsky

2023-02-22 20:01 UTC, voropa requested changes

2023-02-22 20:01 UTC, voropa commented on src/test/java/elements/FormSep.java
> +public class FormSep extends BaseElement    {
Из названия этого класса не совсем понятно, что это за элемент. Сделайте название более читабельным и понятным

2023-02-22 20:01 UTC, voropa commented on src/test/java/elements/Input.java
> +    private final static String INPUT_LOCATOR = "%s";
А какой смысл тут заводить эту шаблонную строку, лишний код по сути. Можно же сразу в методе делать 
driver.findElement(By.id(id));

2023-02-22 20:01 UTC, voropa commented on src/test/java/elements/RadioButtonReport.java
> +    public void clickReportRadiobutton(String value){
В названии метода не нужно добавлять префикс "report", это же и так понятно из названия класса-декоратора

2023-02-22 20:01 UTC, voropa commented on src/test/java/elements/RadioButtonWorkouts.java
> +    public void clickRadiobuttonWorkouts(String value){
То же самое тут

2023-02-22 20:01 UTC, voropa commented on src/test/java/elements/RadioButtonWorkouts.java
> +    private final static String RADIOBUTTON_FOR_WORKOUTS = "//span[text()='Great']//ancestor::label//input";
Судя по локатору, он не динамический, а значит работает только для одного элемента. Тогда зачем создавать класс-обертку ради одного элемента?

2023-02-22 20:01 UTC, voropa commented on src/test/java/elements/TextArea.java
> +    private final static String TEXTAREA_LOCATOR = "%s";
Тут тоже лишняя эта константа с шаблонной строкой

2023-02-22 20:01 UTC, voropa commented on src/test/java/enums/DistTypeCaloricNeeds.java
> +    MILES("\n" +
Удалите символы переноса строки и пробелы из текстовых значений enum'ов и ищите потом значения по contains()

2023-02-22 20:01 UTC, voropa commented on src/test/java/enums/Gender.java
> +    MALE("  Male", "\n" +
То же самое тут

2023-02-22 20:01 UTC, voropa commented on src/test/java/enums/HeightType.java
> +    INCHES("\n" +
и тут

2023-02-22 20:01 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    protected final static String BUTTON_LOCATOR = "//a[text()='%s']";
Что за константа, она вроде нигде не ииспользуется

2023-02-22 20:01 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    protected final static By SAVE_BUTTON_SETTINGS = By.id("saveButtonSettings");
Плохие названия переменных и методов с индексами 1,2,3,4.
Там на сайте они так и отображаются с индексами?

2023-02-22 20:01 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    protected static String GREEN_BOX = "//h4[text()='%s']";
static модификатор применяют для констант, а у вас это не константа, вы же ее переопределяете в классах-наследниках

2023-02-22 20:01 UTC, voropa commented on src/test/java/modals/WorkoutCalculators/Palladino.java
> +    public void fillFormCalculateIntervalPowerTarget(models.WorcoutCalculators.Palladino palladino) {
Зачем писать тут полное имя паакета и т.д.
можно же добавить import models.WorcoutCalculators.Palladino; сверху файла, а тут указывать только имя класса: Palladino

2023-02-22 20:01 UTC, voropa commented on src/test/java/modals/WorkoutCalculators/Tinman.java
> +    public void fillForm(models.WorcoutCalculators.Tinman tinman)  {
То же самое тут

2023-02-22 20:01 UTC, voropa commented on src/test/java/modals/WorkoutCalculators/Palladino.java
> +    public Palladino(WebDriver driver) {
А почему тут 4 метода fillForm() на одной форме? Или это просто 4 варианта ее заполнения?

2023-02-22 20:01 UTC, voropa commented on src/test/java/models/Hills.java
> +    @Override
А зачем вы тут вручную переопределяете toString(), equlas(), hashCode()? 
@Data же делает это за вас и так? 
или тут есть какая-то дополнительная логка в этих методах?

2023-02-22 20:01 UTC, voropa commented on src/test/java/pages/HeaderNavigate.java
> +    private final static By CALENDAR_BUTTON = By.xpath("//i[@class='icsw16-day-calendar']");
icsw16 - выглядит не очень надежно в локаторе. пересмотрите локаторы в этом классе, сделайте их более надежными

2023-02-22 20:01 UTC, voropa commented on src/test/java/pages/PrintDetailsPage.java
> +    public void getTabList()  {
Название метода не соотвествует тому, что он делает

2023-02-22 20:01 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +    private final static String USER_ICON = "%s";
Опять зачем тут эта лишняя переменная %s)

2023-02-22 20:01 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +    public void waitUserIconPresent()   {
Вместо этой пустой шаблонной строки у вас должно быть 2 поля - локатора: userIcon и userAvatar

2023-02-22 20:01 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +    public void clickSettingsButton(String value)   {
И тут тоже

2023-02-22 20:01 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +                "/src/img/monkey-selfie_custom-7117031c832fc3607ee5b26b9d5b03d10a1deaca-s1100-c50.jpg");
Путь к файлу - это тестовые данные, так что оон не должен быть захардкодан прямо тут в методе, а должен попадать сюда через входной агрумент из теста

2023-02-22 20:01 UTC, voropa commented on src/test/java/tests/PrintWorkoutsTest.java
> +        printDetailsPage.getTabList();
Не забывайте переключаться обратно на основную (первую) вкладку

2023-02-22 20:01 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        hansons = new Hansons(driver);
В названии page классов или модалок лучше добавлять соответсвующий постфикс Page или Modal

2023-02-24 16:36 UTC, Alexeyvolsky commented on src/test/java/modals/WorkoutCalculators/Palladino.java
> +    public Palladino(WebDriver driver) {
Там в одной модалке 4 калькулятора.
![image](https://user-images.githubusercontent.com/115730329/221235119-663399a7-eeba-4575-a430-67e5cd4676ac.png)

2023-02-24 16:42 UTC, Alexeyvolsky commented on src/test/java/models/Hills.java
> +    @Override
Так сделано чтобы сравнивало все кроме даты.
Дата вводится в формате 23/02/2023 а выводится Thursday, February 23, 2023

2023-02-24 17:18 UTC, Alexeyvolsky commented on src/test/java/tests/PrintWorkoutsTest.java
> +        printDetailsPage.getTabList();
На той странице тест и заканчивается. Для чего переключаться на основную?

2023-02-24 17:55 UTC, Alexeyvolsky commented on src/test/java/enums/DistTypeCaloricNeeds.java
> +    MILES("\n" +
//label[contains(text(), '%s')]/input
Локатор с contains именно для radiobutton не работает

2023-02-24 17:55 UTC, Alexeyvolsky commented on src/test/java/enums/Gender.java
> +    MALE("  Male", "\n" +
//label[contains(text(), '%s')]/input
Локатор с contains именно для radiobutton не работает

2023-02-24 17:56 UTC, Alexeyvolsky commented on src/test/java/enums/HeightType.java
> +    INCHES("\n" +
//label[contains(text(), '%s')]/input
Локатор с contains именно для radiobutton не работает

2023-02-24 19:30 UTC, voropa commented on src/test/java/enums/DistTypeCaloricNeeds.java
> +    MILES("\n" +
Ок, тогда попробуйте вот что:
Ищите radio-button по двум атрибутам: name и value.
Value храните в enum по типу MILES('miles', 'm')
И затем при использовании декоратора будет как-то так:
new RadioButton(driver, 'DistType', DistTypeCaloricNeeds.MILES.getValue())
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/14195681/221273356-c51bc99f-d184-41a7-8c35-fd081ddee787.png">

2023-02-24 19:30 UTC, voropa commented on src/test/java/tests/PrintWorkoutsTest.java
> +        printDetailsPage.getTabList();
Ок, логично, но допустим, в дальнейшем вы добавите еще один тест в этот класс и он будет падать, потому что вы забыли переключиться обратно в прошлом тесте. Так что переключаться обратно, так же как и закрывать за собой драйвер/конекшн - хорошая привычка, которая обезопасит в дальнейшем

2023-02-24 19:35 UTC, voropa requested changes

2023-02-24 19:35 UTC, voropa commented on src/test/java/elements/GetElementValue.java
> +public class GetElementValue extends BaseElement    {
Тоже странное название, похоже на название метода (глагол), а название классов, обьектов ии переменных должно быть имя существительное.

2023-02-24 19:35 UTC, voropa commented on src/test/java/pages/PrintDetailsPage.java
> +    public void switchBetweenTabs()  {
В таком случае лучше сделать входной аргумент в этом методе и передвать тужа индекс вкладки, на которую нужнор переклбчиться, а не хардкодить его внутри

2023-02-27 18:04 UTC, voropa requested changes

2023-02-27 18:04 UTC, voropa commented on src/test/java/pages/CalendarPage.java
> +    private final static By KSND = By.xpath("    //td[@data-day='10']//div[@class='fc-event-activity-title']");
А чего тут много пробелов перед //td в локаторе?

2023-02-27 18:04 UTC, voropa commented on src/test/java/pages/CalendarPage.java
> +    public void clickNeedData() {
Почему в этих методах захардкоданы какие-то значения 10, 11? вынесите их во входные аргументы

2023-02-27 18:04 UTC, voropa commented on src/test/java/pages/DailyVitalsPage.java
> +        List<WebElement> amountOfDays= driver.findElements(By.xpath("//tbody/tr/td/a"));
Почему локаторы захардкоданы тут? Они должны быть в полях page класса, перенесите их туда

2023-02-27 18:04 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +    public void sendKeysInSettings()    {
Тут то же самое. Почему захардкоданы значения? Они должны быть во входных аргумментах метода

2023-02-27 18:04 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +    public void jsSendKeysInSettings(String name, String value) {
Такой метод во-первых нужно сделать private или protected, а не publicю Во-вторых обычно такиие мметоды выносят в basePage, чтобы потом можно было переиспользовать в других классах по-необходимости

2023-02-27 18:04 UTC, voropa commented on src/test/java/pages/WorkoutLibraryPage.java
> +    private final static By ACTUAL_ACTIVITY_TYPE = By.xpath("//table[contains(@class,'table table-condensed table-hover')]/tbody/tr[1]/td[1]");
Локаторы с ииндексами в таблице выглядят не очень надежными? Там нет возможности зацепиться, например, за кокой-нибудь label / названиие колонки и потом через sibling / ancestor дойти до нужной ячейки?

2023-02-27 18:04 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +//
Почему закоментировано?

2023-03-01 18:44 UTC, Alexeyvolsky commented on src/test/java/pages/WorkoutLibraryPage.java
> +    private final static By ACTUAL_ACTIVITY_TYPE = By.xpath("//table[contains(@class,'table table-condensed table-hover')]/tbody/tr[1]/td[1]");
Нет, такой возможности нет.

2023-03-02 20:00 UTC, voropa requested changes

2023-03-02 20:00 UTC, voropa commented on src/test/java/pages/CalendarPage.java
> +            "font-size: 11px; margin-top: 0px; padding-top: 0px; padding-bottom: 5px;')]//a[text()='%s']";
Очень плохой локатор, который ссылается на style элемента. перестанет работать, как только дабавят/ поменябт какой-то стиль

2023-03-02 20:00 UTC, voropa commented on src/test/java/pages/CalendarPage.java
>      public String getExpectedActivityName() {
Почему метод в Page класссе называется "get**Expected.**.."? Expected - это тестовые данные, в page классах мы только actual данные можем получать

2023-03-02 20:00 UTC, voropa commented on src/test/java/pages/SettingDetailsPage.java
> +    public void sendKeysInSettings()    {
Все равно не правильно) Даже если вы их с помощью faker генерируете, то они должны генерироваться в тесте, а сюда поступать через входные аргументы в методе

2023-03-02 20:00 UTC, voropa commented on src/test/java/pages/Retry.java
> +public class Retry implements IRetryAnalyzer {
Почему у вас Retry и TestListener лежат в пакете pages? Обвчно такие вещи складывают в пакет utils

2023-03-02 20:00 UTC, voropa commented on src/test/java/tests/CopyDayTest.java
> +        calendarPage.clickPlusButton("11");
А что такое 11? Когда читаешь шаги этих тестов, не понятно почему именно 11. Заведите enum какой-нибудь с названием говорящим и тамм добавьте ему value = 11 или еще как-то, чтобы было понятно из контекста теста

2023-03-02 20:00 UTC, voropa commented on src/test/java/tests/CopyDayTest.java
> +        calendarPage.clickPlusButton("10");
тут тоже 10

2023-03-02 20:00 UTC, voropa commented on src/test/java/tests/PallandinoCalculatorTest.java
> +        baseModal.openIframeWorkoutCalculator();
Заметил, что много где вы вызываеете методы из baseModal и это неправильно. bbaseModal вообще по идее, как и осталььные base-классы должен быть абстракным и вы не должны создавать его экземпляр и вызывать методы. Для этоого вы наследуетесь от него и используете конкретные модалки с конкретным названием и функционалом, при этом в них есть весь функциоонал из baseModal. 
поэтому в тестаХ, там где вы используете baseModal переделайте вызовы на конкретные модалки, на которых вы сейчас находитесь по логике теста.

2023-03-05 20:10 UTC, voropa requested changes
Когда вы пишете лог внутри метода и в этом методе есть входной аргумент(ы), то он(и) должны попадать в сообщение лога, чтобы логи получались не статичными по тиипу "я сейчас тут", а динамически отображали те данные и шаги, которые сейчас выполняются

2023-03-05 20:10 UTC, voropa commented on src/test/java/elements/Dropdown.java
>      public void selectOption(String name, String optionName) {
переименуйте лучше в selectOptionByValue(), чтобы было более поонятно на фоне второго метода

2023-03-05 20:10 UTC, voropa commented on src/test/java/tests/BaseTest.java
>      protected final static String BASE_URL = "https://log.finalsurge.com/";
BASE_URL  тоже занесите в config.properties

2023-03-05 20:10 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +            if (headless.equals("false"))    {
Странная логика) если false, то дообавить '--headless'
Вроде должно быть наоборот)

2023-03-05 20:10 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    @Parameters({"browser", "headless"})
а это вы headlessпараметр вычитываете из tsetng.xml фалйов, но у вас там его нигде нет, он не будет тут работать. Есл и вы хотите его из Jenkins вычитывать, то это нужно делать через System.getProperty().
А вот эта аннотация @Parameters из testbg.xml файлов берет параметры.
И  вместе они работать не будут (@Parameters и  system.getProperty()).
Вам нужно определиться, как вы хотите сделать:
1. Либо все параметры в testng.xml файлах ии читаете их через @Parameters как сейчас, но тогда нет смысла делать параметризированный pipeline в Jenkins, параметры из него не попадут в ваш тест никак. 
2. Делаете через Jenkins параметры и считываете их через systtem.getProperty()

2023-03-05 20:10 UTC, voropa commented on src/test/java/elements/Input.java
> +    public void setValueCountry(By locator, String value) {
Это еще что за метод внутри декоратора, он же не имеет к нему никакого отношения

2023-03-05 20:10 UTC, voropa commented on src/test/java/elements/Input.java
> +    public void setValueCountry(String id, String value){
Почему перименовали в setValueCountry? Чем просто setValue плохо?

2023-03-05 20:10 UTC, voropa commented on src/test/java/models/Checkout.java
> +public class Checkout {
Странное название) Checkout  - это глагол) Лучше назвать этот обьект PaymentData

2023-03-05 20:10 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    @Step("Wait for element displayed")
На такие ниизкоуровневые методы и действия обычно не вешают анотацию @Step, и логи пишут вида debug, а не info.
@Step отмечают только действия, шаги польщователя, которые потом хорошо ппосмотреть в репорте

2023-03-05 20:10 UTC, voropa commented on src/test/java/pages/CoachPage.java
> +        log.info("setting username");
Плохой лог) 
Хороший должен содержать динамические данные, которые вы вводите:
String.format("setting username: %s", emial)

2023-03-06 20:45 UTC, voropa requested changes

2023-03-06 20:45 UTC, voropa commented on src/test/java/elements/Input.java
> +    public void setValueCard(By locator, String value) {
Я все равно не пониммаю, какое отношение этот метод setValueCard() имеет к декоратору Input? Он же  приниммает в себя локатор и value, находит элеемент по локатору и выставляем ему значение. С таким же успехом этот метод можно добавить вообще в любой класс в вашем фреймворке. 
Суть в том, что его не должно быть тут

2023-03-06 20:45 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public void setUp(ITestContext testContext) throws Exception    {
Если вы все же решили считывать параметры из jenkins'a (точнее из команды mvn clean test), то нужно подкорректировать ваши suite.xml файлы. В них же по 2 <test> тэга с разными браузерами, но это теперь не будет так работать, у вас будут просто одни и те же тесты на одном и том же браузере 2 раза подряд запускаться, а точнее параллельно, если у вас там стоит parrallel =true. Разберитесь с этим вопросом внимательно

2023-03-06 20:49 UTC, voropa commented
С логами вы сейчас переделали все вызовы с logger.log() на logger.debug(), но это тоже неправильно. 
В debug() нужно писать техническую информацию, которая не имее тотношенияв бизнес-лоогике продукта, например jsClick, поиск локатора, ожидание элемента.
А в info() нужно писать пользовательские действия, которые совершает тест, например, clickButton, setValue.
Перепроверьте все свои логи и поправьте.
Заодно пеерепроверьте, везде ли вы добавили в логи параметры - вхоодные аргументы метродов, если таковые имеются

2023-03-07 19:25 UTC, voropa requested changes

2023-03-07 19:25 UTC, voropa commented on src/test/java/modals/WorkoutCalculators/PalladinoModal.java
> +        log.debug("opening iframe for modal workout calculator");
Сейчас только заметил, что у вас во многих классах-модалках один и тот же метод openIframeWorkoutCalculator() rкоторый делает то же самое с таким же локатором.
Вынесите его в baseModal, чтобы не дублировать код
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/14195681/223529688-ea27abe5-dc60-4784-afba-ae2f14152a94.png">

2023-03-08 20:57 UTC, voropa requested changes

2023-03-08 20:57 UTC, voropa commented on src/test/java/modals/OtherCalculators/CaloricNeedsModal.java
> +        openIframe(LOCATOR_IFRAME_OTHER_CALCULATOR);
Так у вас все равно во всех этих классах одинаковые методы public void openIframeOtherCalculator(), которые внутри вызывают openIframe(LOCATOR_IFRAME_OTHER_CALCULATOR) с одним и тем же локатором. 
Просто перенести всесь метод public void openIframeOtherCalculator() в BaseModal ил создайте просто BaseCalculatorModal и от него унаследуйтесь. А втех классах, где LOCATOR_IFRAME_OTHER_CALCULATOR локатор другой, вы просто переопределите сам локатор, но не нужно дублировать один и тот же метод везде

2023-03-08 20:57 UTC, voropa commented on src/test/java/modals/OtherCalculators/CaloricNeedsModal.java
> +    public void waitSaveButton()    {
То же самое с этим методом, он у вас одинаковый во многих моодалках с одинаковым локатором

2023-03-08 20:57 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +        log.debug("opening iframe");
Сюда хорошо бы добавить информацию о том, какой именн оiframe открывается, добавить locator в лог

2023-03-09 18:35 UTC, voropa reviewed
Видите, как много лишнего кода  можно удалить, если следовать принципам ООП и пользоваться его возможностями)

2023-03-09 18:35 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    public void openIframe()    {
Название метода все же лучше оставить "openIframeCalculator" или в таком духе, чтобы в шагах теста было понятно, какой iFrame открывается. А лучше даже не open, a switchToIFrame...

2023-03-09 18:35 UTC, voropa commented on src/test/java/modals/BaseModal.java
> +    public void waitSaveButton()    {
А этот метод лучше назвать waitForSaveButtonDisplayed()

2023-03-09 19:07 UTC, voropa approved these changes

2023-03-09 19:11 UTC, merged